### PR TITLE
Increased the size of available stack and heap memory in the enclave

### PR DESCRIPTION
**Pull request by reuvenpo**
The stack now has 8MiB.
The heap is now 1GiB.

### CODE REVIEW

**Review by assafmo — APPROVED** [review]

**Comment by lacabra** [comment]
Seriously? It was that simple? 😅 Thanks @reuvenpo 🙏

**Comment by reuvenpo** [comment]
Yeah, haha, sure thing @lacabra :D

**Comment by assafmo** [comment]
Yeah the downside is that SGX allocates the entire hepp in advance therefore startup time is slower now. 4 GiB heap on a high-end computer takes at least one minute to start up, so you should probably play with this value until you get the start-up time you want.

**Comment by lacabra** [comment]
Great insight! Thanks @assafmo

**Pull request merged**
